theme: jekyll-theme-slate
title: Welcome to Edwin's home page!
description: I believe technology empowers others so that they could achieve more, by improving efficiency and streamlining people's way of living. That’s why I have stepped into the world of programming after years in the investment management industry.
